### ISSUE TITLE
Как передать тип Дата?

### ISSUE THREAD

**Issue by Malfarion** [ripreal/androidUtils1cExt#1]
Здравствуйте, подскажите пожалуйста как передать тип Дата из 1С в  ВК JAVA(Android)
methodID_getByDate = jenv->GetMethodID(cc, "getByDate", "(java/utils/Date;)Ljava/lang/String;");

**java/utils/Date;**

**Comment by ripreal** [comment]
Это слишком сложный тип. Рекомендую использовать timestamp, т.е. число миллисекунд с 1970 года, используя при этом тип Long. Это будет отрабатывать как на стороне 1С, так и на JAVA

**Comment by Malfarion** [comment]
Спасибо, как запасной вариант да, но хочется красиво. Дело в том что согласно доке тип "Дата" так-же доступен для передачи, причем судя по всему он кастится в Double
VTYPE_DATE соответствует значению даты и находится в date;

**Comment by ripreal** [comment]
Пришлось столкнутся с задачей передачи даты.
```
tVariant returnValue;
tVariant param;
param.vt = VTYPE_PWSTR;
param.pwstrVal = (uint16_t *) u"time.google.com";
bool result = native->CallAsFunc(AddInNative::Methods::eMethGetExactTime, &returnValue,
                                 &param, 1);
```

Сам метод eMethGetExactTime выглядит так 
```
uint64_t MainApp::getExactTime(std::string ntpServer) {
    if (!obj) {
        return 0;
    }
    JNIEnv *env = getJniEnv();
    jmethodID methID = env->GetMethodID(cc, "getNTPTime", "(Ljava/lang/String;)J");
    jstring server = Utils::stringToJstring(env, ntpServer);
    uint64_t res = env->CallLongMethod(obj, methID, server);
    env->DeleteLocalRef(server);
    return res;
}
```

Метод на стороне java такой

```
  public long getNTPTime(String ntpServer) {
      try {
          return TimeUtils.getNTPTime(ntpServer);
      } catch (Exception e) {
          processError(e);
          return 0;
      }
  }


```
Надеюсь код будет полезен

**Comment by Malfarion** [comment]
Спасибо. Да, но вы передаете дату строкой.
Действительно обходных путей много, но хотелось дату передать именно как дату.

**Comment by ripreal** [comment]
Это аргумент - строка. А возвращаемое значение будет самая настоящая ``Дата``.  Я описал вариант работы с типом в возвращаемом значении функции Компонента -> 1c. При работе с параметром метода подход по идее - все будет  точно также, но наоборот
