### ISSUE TITLE
Добавил свою процедуру виснет намертво.

### ISSUE THREAD

**Issue by HarmfulNick** [ripreal/androidUtils1cExt#2]
public void toast(String message)
  {
      Toast.makeText(m_Activity.getApplicationContext(), message, Toast.LENGTH_LONG).show();
  }
может не так собираю, при этом в андроид студио всё работает.

**Comment by ripreal** [comment]
Забудьте об экранных формах андроида во внешней компоненте

**Comment by HarmfulNick** [comment]
на самом деле мне нужно, вышибает 1с, как с вами связаться
  public boolean MsConnectSQL(String ip, String port, String database, String username,String password) {

    if (connection==null)
    {
    String url = "jdbc:jtds:sqlserver://"+ip+":"+port+"/"+database;

    try {
      Class.forName("net.sourceforge.jtds.jdbc.Driver");
      //Class.forName(Classes);
      connection = DriverManager.getConnection(url, username,password);
      return true;
    } catch (ClassNotFoundException e) {
      e.printStackTrace();
      return false;
    } catch (SQLException e) {
      e.printStackTrace();
      return false;
    }
    }
    else {
      return true;
    }
  }

**Comment by ripreal** [comment]
Я не занимаюсь частными консультациями. На вопросы "как сделать, чтобы у меня все было хорошо" не отвечаю. Конкретный вопрос - конкретный ответ

**Comment by HarmfulNick** [comment]
У меня есть конкретная разработка и бюджет на неё, мне необходим человек который за плату её допилит - при вашем опыте думаю займет часа 3. Все процедуры(3 шт.) готовы надо только их обернуть во внешнею компоненту.

**Comment by HarmfulNick** [comment]
skype  HarmfulNick

**Comment by HarmfulNick** [comment]
Кстати здесь https://github.com/alexkmbk/AndroidTinyToolsFor1C работает вывод сообщения и сборки идет без VS
